package proyectop1_juliocarcamo;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Pokechan extends javax.swing.JFrame {

    public Pokechan() {
        initComponents();
        Listar.setVisible(false);
        Registro.setVisible(false);
        Revision.setVisible(false);
    }
    //si *2

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Listar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Registro = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Tj_Nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Tj_Tipo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Tj_Region = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Tj_Salud = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Revision = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Listar.setBackground(new java.awt.Color(255, 204, 153));

        jList1.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-eevee-100.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-dratini-100.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-psyduck-100.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-snorlax-100.png"))); // NOI18N

        javax.swing.GroupLayout ListarLayout = new javax.swing.GroupLayout(Listar);
        Listar.setLayout(ListarLayout);
        ListarLayout.setHorizontalGroup(
            ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4522, 4522, 4522))
        );
        ListarLayout.setVerticalGroup(
            ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarLayout.createSequentialGroup()
                .addGroup(ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(ListarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(91, 91, 91))))
            .addGroup(ListarLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.add(Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 650, 620));

        jButton4.setBackground(new java.awt.Color(0, 255, 204));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Salir (pipipi)");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 770, 214, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pokeball-96.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 660, -1, 113));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Listar Pokemon");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pokeball-96.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, 79));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Registro Pokemon");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pokeball-96.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, 113));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Revisar Pokedex fachera!");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 660, -1, -1));

        Registro.setBackground(new java.awt.Color(255, 204, 102));
        Registro.setForeground(new java.awt.Color(255, 255, 255));
        Registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Ingrese nombre de pokemon:");
        Registro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 87, 280, -1));

        Tj_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tj_NombreActionPerformed(evt);
            }
        });
        Registro.add(Tj_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 147, 547, -1));

        jLabel9.setText("Ingrese tipo de pokemon");
        Registro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 250, 170, -1));

        Tj_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tj_TipoActionPerformed(evt);
            }
        });
        Registro.add(Tj_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 272, 560, -1));

        jLabel10.setText("Ingrese region de origen de pokemon");
        Registro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 357, 211, -1));

        Tj_Region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tj_RegionActionPerformed(evt);
            }
        });
        Registro.add(Tj_Region, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 406, 550, -1));

        jLabel11.setText("Ingrese puntos de vida del pokemon");
        Registro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 509, 204, -1));
        Registro.add(Tj_Salud, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 560, 550, -1));

        jButton1.setText("Registrar!");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        Registro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 616, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-bulbasaur-100.png"))); // NOI18N
        Registro.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-charmander-100.png"))); // NOI18N
        Registro.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 3, 110, 100));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-squirtle-100.png"))); // NOI18N
        Registro.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 100, 90));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-caterpie-100.png"))); // NOI18N
        Registro.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, 90, 70));
        Registro.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, 120, 40));

        jPanel2.add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 101, 650, 720));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectop1_juliocarcamo/180619084-a56960ab-7efa-4e34-9d33-4e3e581d62ff.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 450, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pokemon-trainer-96.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 690, 100, 80));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pokestop-azul-96.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pokedex-100.png"))); // NOI18N

        javax.swing.GroupLayout RevisionLayout = new javax.swing.GroupLayout(Revision);
        Revision.setLayout(RevisionLayout);
        RevisionLayout.setHorizontalGroup(
            RevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RevisionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        RevisionLayout.setVerticalGroup(
            RevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RevisionLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(RevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel22))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jPanel2.add(Revision, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 175, 420, 510));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_Pngtree_trendy_activity_flat_bo.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -140, 2030, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        ArrayList<String> regiones = new ArrayList<>();
        ArrayList<Integer> conteoRegiones = new ArrayList<>();

        for (Pkemon pichu : Pokemon) {
            String region = pichu.getRegion();

            if (regiones.contains(region)) {
                int i = regiones.indexOf(region);
                conteoRegiones.set(i, conteoRegiones.get(i) + 1);

            } else {
                regiones.add(region);
                conteoRegiones.add(1);
            }
        }
        String j = "";
        
            for (int i = 0; i < regiones.size(); i++) {
                j += regiones.get(i) + ":" + conteoRegiones.get(i) + "\n";
            }
        

        JOptionPane.showMessageDialog(this, "Pokemones registrados : " + Pokemon.size() + "\n" + j);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        actualizar();
        Listar.setVisible(true);
        Registro.setVisible(false);
        Revision.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Listar.setVisible(false);
        Registro.setVisible(true);
        Revision.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void Tj_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tj_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tj_NombreActionPerformed

    private void Tj_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tj_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tj_TipoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        Pkemon P = new Pkemon(Tj_Nombre.getText(), Tj_Tipo.getText(), Tj_Region.getText(), Integer.parseInt(Tj_Salud.getText()));
        Pokemon.add(P);
        JOptionPane.showMessageDialog(this, "Tu pokemon se ha registrado con extito!");
        Tj_Nombre.setText("");
        Tj_Tipo.setText("");
        Tj_Region.setText("");
        Tj_Salud.setText("");

    }//GEN-LAST:event_jButton1MouseClicked

    private void actualizar() {
        DefaultListModel m = (DefaultListModel) jList1.getModel();
        m.removeAllElements();
        for (Pkemon pkemon : Pokemon) {
            m.addElement(pkemon);
        }
        jList1.setModel(m);
    }


    private void Tj_RegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tj_RegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tj_RegionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pokechan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pokechan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pokechan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pokechan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pokechan().setVisible(true);
            }
        });
    }
    ArrayList<Pkemon> Pokemon = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Listar;
    private javax.swing.JPanel Registro;
    private javax.swing.JPanel Revision;
    private javax.swing.JTextField Tj_Nombre;
    private javax.swing.JTextField Tj_Region;
    private javax.swing.JTextField Tj_Salud;
    private javax.swing.JTextField Tj_Tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}