/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectop1_juliocarcamo;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jucec
 */
public class Pokechan extends javax.swing.JFrame {

    /**
     * Creates new form Pokechan
     */
    public Pokechan() {
        initComponents();
        Listar.setVisible(false);
        Registro.setVisible(false);
        Revision.setVisible(false);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Listar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Registro = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Tj_Nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Tj_Tipo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Tj_Region = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Tj_Salud = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Revision = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Listar.setBackground(new java.awt.Color(204, 204, 204));

        jList1.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout ListarLayout = new javax.swing.GroupLayout(Listar);
        Listar.setLayout(ListarLayout);
        ListarLayout.setHorizontalGroup(
            ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ListarLayout.setVerticalGroup(
            ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 780, 740));

        jButton4.setBackground(new java.awt.Color(0, 255, 204));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Salir (pipipi)");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 698, 214, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pokeball-96.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 552, -1, 113));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Listar Pokemon");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 253, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pokeball-96.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 281, -1, 79));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Registro Pokemon");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pokeball-96.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 402, -1, 113));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Revisar Pokedex fachera!");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 530, -1, -1));

        Registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Ingrese nombre de pokemon:");
        Registro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 87, 280, -1));

        Tj_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tj_NombreActionPerformed(evt);
            }
        });
        Registro.add(Tj_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 147, 547, -1));

        jLabel9.setText("Ingrese tipo de pokemon");
        Registro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 250, 170, -1));

        Tj_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tj_TipoActionPerformed(evt);
            }
        });
        Registro.add(Tj_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 272, 709, -1));

        jLabel10.setText("Ingrese region de origen de pokemon");
        Registro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 357, 211, -1));

        Tj_Region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tj_RegionActionPerformed(evt);
            }
        });
        Registro.add(Tj_Region, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 406, 709, -1));

        jLabel11.setText("Ingrese puntos de vida del pokemon");
        Registro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 509, 204, -1));
        Registro.add(Tj_Salud, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 560, 709, -1));

        jButton1.setText("Registrar!");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        Registro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 616, -1, -1));

        jPanel2.add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 6, -1, 735));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectop1_juliocarcamo/180619084-a56960ab-7efa-4e34-9d33-4e3e581d62ff.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 470, 160));

        javax.swing.GroupLayout RevisionLayout = new javax.swing.GroupLayout(Revision);
        Revision.setLayout(RevisionLayout);
        RevisionLayout.setHorizontalGroup(
            RevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3746, Short.MAX_VALUE)
        );
        RevisionLayout.setVerticalGroup(
            RevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addComponent(Revision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(870, 870, 870))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(583, 583, 583)
                .addComponent(Revision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(703, 703, 703))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Listar.setVisible(false);
        Registro.setVisible(false);
        Revision.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        actualizar();
        Listar.setVisible(true);
        Registro.setVisible(false);
        Revision.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Listar.setVisible(false);
        Registro.setVisible(true);
        Revision.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void Tj_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tj_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tj_NombreActionPerformed

    private void Tj_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tj_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tj_TipoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        Pkemon P = new Pkemon(Tj_Nombre.getText(), Tj_Tipo.getText(), Tj_Region.getText(), Integer.parseInt(Tj_Salud.getText()));
        Pokemon.add(P);
        JOptionPane.showMessageDialog(this, "Se agrego correctamente");
        Tj_Nombre.setText("");
        Tj_Tipo.setText("");
        Tj_Region.setText("");
        Tj_Salud.setText("");

    }//GEN-LAST:event_jButton1MouseClicked

    private void actualizar(){
        DefaultListModel m = (DefaultListModel) jList1.getModel();
        m.removeAllElements();
        for (Pkemon pkemon : Pokemon) {
            m.addElement(pkemon);
        }
        jList1.setModel(m);
    }
    
    
    private void Tj_RegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tj_RegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tj_RegionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pokechan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pokechan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pokechan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pokechan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pokechan().setVisible(true);
            }
        });
    }
    ArrayList<Pkemon> Pokemon = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Listar;
    private javax.swing.JPanel Registro;
    private javax.swing.JPanel Revision;
    private javax.swing.JTextField Tj_Nombre;
    private javax.swing.JTextField Tj_Region;
    private javax.swing.JTextField Tj_Salud;
    private javax.swing.JTextField Tj_Tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
